### ISSUE TITLE
Container_port.create is always partially applied

### ISSUE THREAD

**Issue by rizo** [andrenth/kubecaml#2]
The signature of the `Kubecaml.Kubernetes.Definitions.Api.Core.V1.Container_port.create` function does not include the unit argument needed to force the application. This means that all labeled arguments need to be supplied to actually create the value. If only some of the arguments are provided the call results in a partial application.

Here's the demonstration:

```ocaml
# #require "kubecaml";;
# Kubecaml.Kubernetes.Definitions.Api.Core.V1.Container_port.create
     ~name:"xxx"
     ~container_port:8080;;
- : ?protocol:string ->
    ?host_port:int ->
    ?host_ip:string ->
    Kubecaml.Kubernetes.Definitions.Api.Core.V1.Container_port.t
= <fun>
# Kubecaml.Kubernetes.Definitions.Api.Core.V1.Container_port.create
     ~name:"xxx"
     ~container_port:8080
     ?protocol:None
     ?host_port:None
     ?host_ip:None;;
- : Kubecaml.Kubernetes.Definitions.Api.Core.V1.Container_port.t = <abstr>
```

I'm not sure if this should be reported in the swagger generator library.

**Comment by rizo** [comment]
For reference this is what `ppx_deriving.make` produces:

```ocaml
(* From the generated kubecaml.ml: *)
type t = {
  protocol : (string option [@default None]);
  name : (string option [@default None]); 
  host_port : (int option [@default None]) [@key "hostPort"]; 
  host_ip : (string option [@default None]) [@key "hostIP"]; 
  container_port : int [@key "containerPort"];
} [@@deriving make];;

val make :
  ?protocol:string option ->
  ?name:string option ->
  ?host_port:int option ->
  ?host_ip:string option -> container_port:int -> unit -> t 
```

Maybe you can use `ppx_deriving.make` instead of generating a custom `create` function?

Let me know what you think about this, I can try submitting a PR for this.

**Comment by rizo** [comment]
I submitted a [PR to fix this issue](https://github.com/andrenth/ocaml-swagger/pull/1). I still think using `ppx_deriving.make` is a good idea.

**Comment by rizo** [comment]
For reference this issue is solved by https://github.com/andrenth/ocaml-swagger/pull/1.

@andrenth Should I close this issue? Or should I keep it until the new version of ocaml-swagger is released?

**Comment by andrenth** [comment]
Please leave it open. I’ll try to make (create? :) new releases by the end of the week (haven’t been using OCaml recently so I’m a bit short on time).

**Comment by shonfeder-da** [comment]
Looks like there was a release of ocaml-swagger in October: https://github.com/andrenth/ocaml-swagger/releases

(Just a distantly interested party passing by :) )

**Comment by rizo** [comment]
I'm going to close this. We should release kubecaml soon anyway.
